### PR TITLE
Diplomacy fixes and upgrades

### LINKED ISSUE #283: Bug: Satellites of nations that disappear during conversion retain satellite status although overlord doesn't exist.
In my case Huastec was a vassal of Matlezinca, which itself got deleted due to province disappearing during conversion. As a result, Huastec is still a satellite but without an overlord it cannot be targeted nor can perform diplomacy freely.

sattelite_bug

### LINKED ISSUE #338: Enhancement: Expand recognized diplomacy relations
Explain to EU4Diplomacy the meaning of client_state, client_march, tributary and others.
Can shove some of them into substates which Vic2 actually recognizes.
While at it rewrite the parser from scratch.

### PR DESCRIPTION
**Pull request by Zemurin**
- fixed #283 
- fixed #338 
- agreement_types.txt now allows for updating new agreement types without hardcoding
- tributaries and vassals now start sphered
- military access distributed across vassals and tributaries
- starting influence generated from relations and vassal status (where applicable)
- starting influence automatically spent to increase relations level

### CODE REVIEW

File: EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp [hunk 1]
```diff
@@ -63,46 +68,106 @@ void V2::Diplomacy::convertDiplomacy(
...
-		// In essence we only have 3 diplomacy categories and these are it.
+		// In essence we should only recognize 3 diplomacy categories and these are it.
 		if (agreement.getAgreementType() == "alliance" || agreement.getAgreementType() == "vassal" || agreement.getAgreementType() == "guarantee")
 		{
 			// copy agreement
 			Agreement v2agreement(V2Tag1, V2Tag2, agreement.getAgreementType(), agreement.getStartDate());
 			agreements.push_back(v2agreement);
 		}
 	}
+	// Now, alter prestige of vassals.
```
Comment (Idhrendur) [inline EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp]: It won't let me comment above, but convertDiplomacy() is really long and doing several discrete tasks at multiple levels of abstraction. Most or all of the work should be put into functions called by convertDiplomacy()

File: EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp [hunk 2]
```diff
@@ -63,46 +68,106 @@ void V2::Diplomacy::convertDiplomacy(
...
+	for (const auto& conglomerate: masterVassals)
+	{
+		const auto& masterDev = masterCache[conglomerate.first];
```
Comment (Idhrendur) [inline EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp]: I'm not overly fond of the [] operator on maps. It can cause changes in the map. While the overall logic of this function makes that impossible (as conglomerate.first is always there), it's not clear if you're looking at this in isolation. Better to use .find(), even though that adds to the length.

File: EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp (hunk 1 above)
Comment (Zemurin) [reply EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp]: done, we have 5-6 new functions now coming from in there dealing with discrete tasks.

File: EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp (hunk 2 above)
Comment (Zemurin) [reply EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp]: I think you worry too much here. Earlier I have this line:
`masterVassals[V2Tag1].insert(V2Tag2);`
It doesn't check if V2Tag1 is in map nor if there exists a set to store it, or if the value is actually stored. C++ handles all of this, which is the beauty of maps.

When iterating over a map with a const auto& I know the map is immutable, so no worries of changing anything. I'd like to reserve iterator-incrementing loops or .find() for instances where one has to alter the element within the map.

For this particular case, I think find() would be excessive and harder to read (at least to me).
