### PR TITLE
Culture Mapper fixes

### LINKED ISSUE #142: Religious-regional cultures not working
It seems as the converter doesn't care about the various lines in the culture mapping file that teaches it to, e.g. make the Muslim Serbians Bosnjaks or remembering that British people in Canada are "Anglo Canadian".

I don't know if it may be tied with order as in #507, but in doubt, I post it here, as it is an annoying bug and may cause cultural-core problems.

### LINKED ISSUE #149: Multiple distinguishers of the same kind in culture maps
Many culture mapping use multiple `region` distinguishers, however only one distinguisher of each type is allowed by the converter for a single culture mapping. This seems to be the case for the more recent colonial cultures (e.g. amerikaner), while some older ones make multiple mapping rules for the same destination culture if there are more than one source region. I wonder if this is intentional (regex used in code seems to indicate that it is; it also makes sense to demand all distinguisher to be satisfied, and hence allow at most one of each kind). If so, culture mappings need fixing.

### PR DESCRIPTION
**Pull request by Zemurin**
- Fixed #149
- Fixed #142
Culture mapper will now properly parse superregions as well as individual areas. It now supports multiple distinguishers of any kind, or none at all, aside for incoming and outgoing culture.

### CODE REVIEW

File: EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp [hunk 1]
```diff
@@ -8,30 +10,71 @@ mappers::CultureMappingRule::CultureMappingRule(std::istream& theStream)
...
+		});
+	registerKeyword("owner", [this](const std::string& unused, std::istream& theStream)
+		{
+			commonItems::singleString ownerStr(theStream);
+			owners.insert(ownerStr.getString());
+		});
+	registerKeyword("provinceid", [this](const std::string& unused, std::istream& theStream)
+		{
+			commonItems::singleString provinceStr(theStream);
+			if (stoi(provinceStr.getString())) provinces.insert(stoi(provinceStr.getString()));
```
Comment (Idhrendur) [inline EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp]: Std::stoi throws an exception on failure, so try/catch instead of checking with an if

File: EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp [hunk 2]
```diff
@@ -8,30 +10,71 @@ mappers::CultureMappingRule::CultureMappingRule(std::istream& theStream)
...
+				// for the converter to explode across the logs and scream all invalid names. So, continue.
+				continue;
+			}
+			if (EU4Regions.provinceInRegion(EU4Province, region)) regionMatch = true;
+		}
+		if (!regionMatch) return std::nullopt;
 	}
-}
\ No newline at end of file
+	if (match) return destinationCulture;
```
Comment (Idhrendur) [inline EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp]: Codacy called this out as redundant.

File: EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp (hunk 1 above)
Comment (Zemurin) [reply EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp]: Thanx, I was under mistaken impression stoi would return 0 for a non-digit string.

File: EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp (hunk 2 above)
Comment (Zemurin) [reply EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.cpp]: Thanx, fixed.
