### PR TITLE
World & Provinces

### LINKED ISSUE #176: Looking for flags in wrong place
It seems the converter is looking for additional flags in blankMod/output/gfx/flags/, when it should be looking in flags/. If so, this will be a change at the top of mappers::CountryMappings::getAvailableFlags()

### PR DESCRIPTION
**Pull request by Zemurin**
- v2::World cleaned up
- fixed broken cultural unions / nationals data files
- rewrote how provinces are distributed (affects basically everything on initialization)
- fixed missing forts
- fixed broken ports
- fixed #176 (flags in wrong place)
- split v2::world in multiple functions and files where able
- some new parsers to declutter world
- version now loaded from file, hand-editable.

### CODE REVIEW

File: EU4toV2/Source/V2World/V2World.cpp [hunk 1]
```diff
@@ -1,1745 +1,1220 @@
...
+
+	V2CountriesInput.close();
+}
+
+void V2::World::importPotentialCountry(const std::string& line, bool dynamicCountry)
+{
+	std::string tag = line.substr(0, 3);
+
+	auto newCountry = std::make_shared<Country>(line, dynamicCountry, partyNameMapper, partyTypeMapper);
+	potentialCou
```
Comment (Idhrendur) [inline EU4toV2/Source/V2World/V2World.cpp]: It might still be worth shoving in a named constant at the top of the file or somewhere: ```constexpr int MAX_EQUALITY_COUNTRIES = 5;```

Comment (Idhrendur) [inline EU4toV2/Source/V2World/V2World.cpp]: Same: ```constexpr int MAX_LIBERTY_COUNTRIES = 20;```

Comment (Idhrendur) [inline EU4toV2/Source/V2World/V2World.cpp]: I think this was an intentional way of indicating that provinces were unmapped. I'm not sure if the province mapping tool supports this format, which tells you how old it would be.

Either way, it should either be unlogged or removed entirely.

Comment (Idhrendur) [inline EU4toV2/Source/V2World/V2World.cpp]: This value (and much of the related code) is from this group of multiplayer megacampaigners: https://forum.paradoxplaza.com/forum/index.php?threads/bloody-yet-unbowed-ck2-to-hoi4-megacampaign-aar-thread.1243119/

It's very arbitrary stuff done to tweak their mods how they like 'em. Every time they get to the point of converting to Vic2 they tweak the extreme algorithm how they want it. I let them because it's by them, for them. At least I was able to read EU4 buildings from file instead of having hundreds of lines of hard-coded (and wrong) values.

File: EU4toV2/Source/EU4World/Provinces/Provinces.h [hunk 2]
```diff
@@ -14,17 +13,16 @@ namespace EU4
 	{
 	public:
 		Provinces(std::istream& theStream, const mappers::Buildings& buildingTypes, const Modifiers& modifierTypes);
-		Province& getProvince(int provinceNumber);
+		std::shared_ptr<Province>& getProvince(int provinceNumber);
```
[the remark this answers is not in the document]
Comment (Zemurin) [reply EU4toV2/Source/EU4World/Provinces/Provinces.h]: Right! So, if we're not actually assigning the shared pointer to a new object, we should never serve it as a reference - got it.

File: EU4toV2/Source/EU4World/World.h [hunk 3]
```diff
@@ -21,23 +18,21 @@
...
+		std::map<std::string, std::shared_ptr<Country>> getCountries() const { return theCountries; };
 		std::vector<EU4Agreement> getDiplomaticAgreements() const { return diplomacy; };
 		double getTotalProvinceWeights() const { return provinces->geTotalProvinceWeights(); };
 		const Regions& getRegions() const { return *regions; }
-		const Religions& getAllReligions() const { return theReligions; }
-		const EU4::Version& getVersion() const { return *version; };
-		const Province& getProvince(int provNum) const;
+		const Religions& getReligions() const { return theReligions; }
+		const Version& getVersion() const { return *version; }
+		const std::shared_ptr<Province>& getProvince(int provNum) const;
```
[the remark this answers is not in the document]
Comment (Zemurin) [reply EU4toV2/Source/EU4World/World.h]: fixed

File: EU4toV2/Source/V2World/State/State.cpp [hunk 4]
```diff
@@ -80,9 +80,12 @@ void	V2::State::colloectNavalBase()
 	for (auto province : provinces)
 	{
 		if (!prov) prov = province;
-		level += province->getNavalBaseLevel();
-		if (prov->getNavalBaseLevel() < province->getNavalBaseLevel()) prov = province;
+		if (prov->getNavalBaseLevel() < province->getNavalBaseLevel())
```
[the remark this answers is not in the document]
Comment (Zemurin) [reply EU4toV2/Source/V2World/State/State.cpp]: I have no idea what "colloect" means so I'll just rename this.

File: EU4toV2/Source/V2World/V2World.cpp (hunk 1 above)
Comment (Zemurin) [reply EU4toV2/Source/V2World/V2World.cpp]: done

Comment (Zemurin) [reply EU4toV2/Source/V2World/V2World.cpp]: done

Comment (Zemurin) [reply EU4toV2/Source/V2World/V2World.cpp]: Line 219 has nothing to do with provinces, I think you misclicked. Where is the block I need to clean?

Comment (Zemurin) [reply EU4toV2/Source/V2World/V2World.cpp]: Again 291 is not the line you were speaking of. If we're discussing the (0.55 * totalWorldPopulation) from 823, it may even be worth it to slap some of that stuff into an exterrnal config file. I'll need to have a chat with the fellows to see what they require.
